=== aliciafp15/Formula1/xml/p5/circuito.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema xmlns="http://www.uniovi.es" elementFormDefault="qualified"
  targetNamespace="http://www.uniovi.es" 
  xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="circuito">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="datos" />
        <xs:element ref="tramos" />
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="tramos">
    <xs:complexType>
      <xs:sequence>
        <xs:element minOccurs="1" maxOccurs="unbounded" ref="tramo" />
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="datos">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="nombre" />
        <xs:element ref="longitud" />
        <xs:element ref="anchuraMed" />
        <xs:element ref="fecha" />
        <xs:element ref="hora" />
        <xs:element ref="nVueltas" />
        <xs:element ref="localidad" />
        <xs:element ref="pais" />
        <xs:element ref="referencias" />
        <xs:element ref="fotografias" />
        <xs:element ref="videos" />
        <xs:element ref="coordenadas" />
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="nombre" type="xs:string" />
  <xs:element name="longitud" type="xs:decimal" />
  <xs:element name="anchuraMed" type="xs:decimal" />
  <xs:element name="fecha" type="xs:date" />
  <xs:element name="hora" type="xs:time" />
  <xs:element name="nVueltas">
    <xs:simpleType>
      <xs:restriction base="xs:integer">
        <xs:minInclusive value="1" />
      </xs:restriction>
    </xs:simpleType>
  </xs:element>

  <xs:element name="localidad" type="xs:string" />
  <xs:element name="pais" type="xs:string" />


  <xs:element name="referencias">
    <xs:complexType>
      <xs:sequence>
        <xs:element minOccurs="3" maxOccurs="unbounded" ref="referencia" />
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="referencia" type="xs:string" />

  <xs:element name="fotografias">
    <xs:complexType>
      <xs:sequence>
        <xs:element minOccurs="1" maxOccurs="5" ref="foto" />
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="foto" type="xs:string" />
  <xs:element name="videos">
    <xs:complexType>
      <xs:sequence>
        <xs:element minOccurs="0" maxOccurs="3" ref="video" />
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="video" type="xs:string" />


  <xs:element name="coordenadas">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="longitudCircuito" />
        <xs:element ref="latitudCircuito" />
        <xs:element ref="altitudCircuito" />
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="longitudCircuito" type="xs:decimal" />
  <xs:element name="latitudCircuito" type="xs:decimal" />
  <xs:element name="altitudCircuito" type="xs:decimal" />

  <xs:element name="tramo">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="dist" />
        <xs:element ref="coordenadasTramo" />
        <xs:element ref="nSector" />
      </xs:sequence>
      <xs:attribute name="distUnidad" type="xs:string" />
    </xs:complexType>
  </xs:element>

  <xs:attribute name="distUnidad">
    <xs:simpleType>
      <xs:restriction base="xs:string">
        <xs:enumeration value="m" />
        <xs:enumeration value="km" />
      </xs:restriction>
    </xs:simpleType>
  </xs:attribute>

  <xs:element name="dist" type="xs:decimal" />

  <xs:element name="coordenadasTramo">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="longitudTramo" />
        <xs:element ref="latitudTramo" />
        <xs:element ref="altitudTramo" />
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="longitudTramo" type="xs:decimal" />
  <xs:element name="latitudTramo" type="xs:decimal" />
  <xs:element name="altitudTramo" type="xs:decimal" />
  <xs:element name="nSector" type="xs:integer" />
</xs:schema>

=== aliciafp15/Formula1/xml/circuitoEsquema copy.xml
<?xml version="1.0" encoding="UTF-8"?>
<circuito xmlns="http://www.uniovi.es"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://www.uniovi.es circuito.xsd">
    <datos>
        <nombre>Monza</nombre>
        <longitud>5793</longitud>
        <anchuraMed>12</anchuraMed>
        <fecha>2024-09-01</fecha>
        <hora>15:00:00</hora>
        <nVueltas>53</nVueltas>
        <localidad>Monza</localidad>
        <pais>Italia</pais>
        <referencias>
            <referencia>https://es.wikipedia.org/wiki/Autodromo_Nazionale_di_Monza</referencia>
            <referencia>https://www.dazn.com/es-ES/news/motor/circuito-monza-donde-esta-como-es-caracteristicas-como-llegar-fotos-escenario-gp-italia-mundial-f1/1rvwgg1hco88f14fi4ivfb1g00</referencia>
            <referencia>https://www.f1italy.com/es/la-historia-del-circuito-de-monza</referencia>
        </referencias>
        <fotografias>
            <foto>foto.jpeg</foto>
        </fotografias>
        <videos></videos>
        <coordenadas>
            <longitudCircuito>9.281434</longitudCircuito> 
            <latitudCircuito>45.618162</latitudCircuito>
            <altitudCircuito>183</altitudCircuito>
        </coordenadas>
    </datos>
    <tramos>
        <tramo distUnidad="m"><!--p1-->
            <dist>618.53</dist>
            <coordenadasTramo>
                <longitudTramo>9.282124</longitudTramo>
                <latitudTramo>45.624335</latitudTramo>
                <altitudTramo>187</altitudTramo>
            </coordenadasTramo>
            <nSector>1</nSector>
        </tramo>
        <tramo distUnidad="m"><!--p2-->
            <dist>45.06</dist>
            <coordenadasTramo>
                <longitudTramo>9.282133</longitudTramo>
                <latitudTramo>45.624266</latitudTramo>
                <altitudTramo>187</altitudTramo>
            </coordenadasTramo>
            <nSector>1</nSector>
        </tramo>
        <tramo distUnidad="m">
            <dist>155.7</dist><!--p3-->
            <coordenadasTramo>
                <longitudTramo>9.282080</longitudTramo>
                <latitudTramo>45.626000</latitudTramo>
                <altitudTramo>188</altitudTramo>
            </coordenadasTramo>
            <nSector>1</nSector>
        </tramo>
        <tramo distUnidad="m"><!--p4-->
            <dist>330.18</dist>
            <coordenadasTramo> 
                <longitudTramo>9.283529</longitudTramo>
                <latitudTramo>45.628440</latitudTramo>
                <altitudTramo>189</altitudTramo>
            </coordenadasTramo>
            <nSector>1</nSector>
        </tramo>

        <tramo distUnidad="m"><!--p5-->
            <dist>308.78</dist>
            <coordenadasTramo>
                <longitudTramo>9.286833</longitudTramo>
                <latitudTramo>45.629167</latitudTramo>
                <altitudTramo>191</altitudTramo>
            </coordenadasTramo>
            <nSector>1</nSector>
        </tramo>

        <tramo distUnidad="m"><!--p6-->
            <dist>358.21</dist>
            <coordenadasTramo>
                <longitudTramo>9.291183</longitudTramo>
                <latitudTramo>45.629937</latitudTramo>
                <altitudTramo>191</altitudTramo>
            </coordenadasTramo>
            <nSector>2</nSector>
        </tramo>

        <tramo distUnidad="m"><!--p7-->
            <dist>45.22</dist>
            <coordenadasTramo>
                <longitudTramo>9.291183</longitudTramo>
                <latitudTramo>45.629937</latitudTramo>
                <altitudTramo>191</altitudTramo>
            </coordenadasTramo>
            <nSector>2</nSector>
        </tramo>

        <tramo distUnidad="m"><!--p8-->
            <dist>318.7</dist>
            <coordenadasTramo>
                <longitudTramo>9.294464</longitudTramo>
                <latitudTramo>45.629721</latitudTramo>
                <altitudTramo>188</altitudTramo>
            </coordenadasTramo>
            <nSector>2</nSector>
        </tramo>

        <tramo distUnidad="m"><!--p9-->
            <dist>94.66</dist>
            <coordenadasTramo>
                <longitudTramo>9.294464</longitudTramo>
                <latitudTramo>45.629721</latitudTramo>
                <altitudTramo>188</altitudTramo>
            </coordenadasTramo>
            <nSector>2</nSector>
        </tramo>

        <tramo distUnidad="m"><!--p10-->
            <dist>267.67</dist>
            <coordenadasTramo>
                <longitudTramo>9.294882</longitudTramo>
                <latitudTramo>45.629614</latitudTramo>
                <altitudTramo>188</altitudTramo>
            </coordenadasTramo>
            <nSector>2</nSector>
        </tramo>


        <tramo distUnidad="m"><!--p11-->
            <dist>501.63</dist>
            <coordenadasTramo>
                <longitudTramo>9.290705</longitudTramo>
                <latitudTramo>45.627750</latitudTramo>
                <altitudTramo>190</altitudTramo>
            </coordenadasTramo>
            <nSector>2</nSector>
        </tramo>

        <tramo distUnidad="m"><!--p12-->
            <dist>570.98</dist>
            <coordenadasTramo>
                <longitudTramo>9.286630</longitudTramo>
                <latitudTramo>45.623118</latitudTramo>
                <altitudTramo>186</altitudTramo>
            </coordenadasTramo>
            <nSector>3</nSector>
        </tramo>

        <tramo distUnidad="m"><!--p13-->
            <dist>110.8</dist>
            <coordenadasTramo>
                <longitudTramo>9.292550</longitudTramo>
                <latitudTramo>45.635541</latitudTramo>
                <altitudTramo>201</altitudTramo>
            </coordenadasTramo>
            <nSector>3</nSector>
        </tramo>


        <tramo distUnidad="m"><!--p14-->
            <dist>78.92</dist>
            <coordenadasTramo>
                <longitudTramo>9.283913</longitudTramo>
                <latitudTramo>45.622214</latitudTramo>
                <altitudTramo>185</altitudTramo>
            </coordenadasTramo>
            <nSector>3</nSector>
        </tramo>


        <tramo distUnidad="m"><!--p15-->
            <dist>975.9</dist>
            <coordenadasTramo>
                <longitudTramo>9.283768</longitudTramo>
                <latitudTramo>45.613461</latitudTramo>
                <altitudTramo>180</altitudTramo>
            </coordenadasTramo>
            <nSector>3</nSector>
        </tramo>

        <tramo distUnidad="m"><!--p16-->
            <dist>87.69</dist>
            <coordenadasTramo>
                <longitudTramo>9.283289</longitudTramo>
                <latitudTramo>45.612963</latitudTramo>
                <altitudTramo>180</altitudTramo>
            </coordenadasTramo>
            <nSector>3</nSector>
        </tramo>

        <tramo distUnidad="m"><!--p17-->
            <dist>182.59</dist>
            <coordenadasTramo>
                <longitudTramo>9.282269</longitudTramo>
                <latitudTramo>45.614712</latitudTramo>
                <altitudTramo>191</altitudTramo>
            </coordenadasTramo>
            <nSector>3</nSector>
        </tramo>

        <tramo distUnidad="m"><!--p18-->
            <dist>360.46</dist>
            <coordenadasTramo>
                <longitudTramo>9.280868</longitudTramo>
                <latitudTramo>45.616432</latitudTramo>
                <altitudTramo>182</altitudTramo>
            </coordenadasTramo>
            <nSector>3</nSector>
        </tramo>


    </tramos>
</circuito>
